### ISSUE TITLE
How long can we defer?

### ISSUE THREAD

**Issue by XiaoxingChen** [XiaoxingChen/saving_ececs_davis_2020_fall#1]

**Comment by XiaoxingChen** [comment]
![WeChat Image_20200513213946](https://user-images.githubusercontent.com/16934019/81819910-804bb400-9562-11ea-90c4-89bf1630e3d7.jpg)
1. SIR yes
2. complete Deferal of Admission.

**Comment by XiaoxingChen** [comment]
![deferment](https://user-images.githubusercontent.com/16934019/81822588-e6860600-9565-11ea-849d-94cabd9e5ebc.jpg)
The procedure to apply for deferment

**Comment by mingyangSunshine** [comment]
so won't you go this year?

**Comment by XiaoxingChen** [comment]
> so won't you go this year?
May defer to 2020 winter
